@CART_ITEMS_URL=http://localhost:5000/api/v1/cart-items

### GET Cart Items ###
GET {{CART_ITEMS_URL}}

### POST Cart Item ###
POST {{CART_ITEMS_URL}}
Content-Type: application/json

{
    "quantity": 5,
    "cart": {
        "id": "fa60a671-4129-48a3-b3c0-28c4db2c8a20"
    },
    "product": {
        "id": "ebabfabb-c45c-4c30-9d52-83688abe5967"
    }
}

### GET Cart Item ###
GET {{CART_ITEMS_URL}}/e7ec5a00-6a8d-4fa1-b4df-57cf51051415

### PATCH Cart Item ###
PATCH {{CART_ITEMS_URL}}/e7ec5a00-6a8d-4fa1-b4df-57cf51051415
Content-Type: application/json

{
    "quantity": 2
}

### DELETE Cart Item ###
DELETE {{CART_ITEMS_URL}}/69c2732b-6f8a-4dde-8165-831342689a2f