version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommdb
      PG_DATA: /data/postgres
    volumes:
      - ./data:/data/postgres

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    depends_on:
      - db
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ecommdb.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./pgadmin:/root/.pgadmin
      - ./db-servers.json:/pgadmin4/servers.json