@BASE_URL=http://localhost:5000
@API_URL={{BASE_URL}}/api/v1

###
GET {{BASE_URL}}

###
GET {{API_URL}}/users

###
POST {{API_URL}}/users
Content-Type: application/json

{
    "firstName": "Ernest",
    "lastName": "Wambua",
    "email": "ernestwambua4@gmail.com",
    "password": "password123"
}

###
GET {{API_URL}}/users/5de82075-97e6-4f20-9b2d-1c60dbb207ab

###
PATCH {{API_URL}}/users/5de82075-97e6-4f20-9b2d-1c60dbb207ab
Content-Type: application/json

{
    "firstName": "Meshack"
}

###
DELETE {{API_URL}}/users/5de82075-97e6-4f20-9b2d-1c60dbb207ab

###
GET {{API_URL}}/inventories

###
GET {{API_URL}}/inventories/278c59b3-d0f9-4eff-a837-f3ea2502c20b

###
DELETE {{API_URL}}/inventories/278c59b3-d0f9-4eff-a837-f3ea2502c20b

###
GET {{API_URL}}/categories

###
POST {{API_URL}}/categories
Content-Type: application/json

{
    "name": "Accessories"
}

###
GET {{API_URL}}/products

###
POST {{API_URL}}/products
Content-Type: application/json

{
    "name": "Mac lipstick 2",
    "desc": "Mac red lipstick 2",
    "sku": "ABCD1238",
    "category": "4a50ef1c-bb92-422a-8eae-b5951082f04f",
    "inventory": "0fafc7c9-5530-4875-a552-4c05dbd5bbd5",
    "price": 2300.44
}

###
GET {{API_URL}}/products/b6f239ef-36de-4630-9317-496c349e63ba

###
PATCH {{API_URL}}/products/b6f239ef-36de-4630-9317-496c349e63ba
Content-Type: application/json

{
    "name": "addidas slippers"
}

###
DELETE {{API_URL}}/products/5a08a836-8fa3-4909-b9ee-2f7642287512

###
GET {{API_URL}}/product-categories

###
POST {{API_URL}}/product-categories
Content-Type: application/json

{
    "name": "accessories",
    "desc": "general accessories"
}

###
GET {{API_URL}}/product-categories/9d48e6a6-0bc5-42b1-972f-06f6e63ff833

###
PATCH {{API_URL}}/product-categories/9d48e6a6-0bc5-42b1-972f-06f6e63ff833
Content-Type: application/json

{
    "desc": "general indoor/outdoor accessories"
}

###
DELETE {{API_URL}}/product-categories/9d48e6a6-0bc5-42b1-972f-06f6e63ff833