@BASE_URL=http://localhost:5000/api/v1

###
GET {{BASE_URL}}

### GET Products ###
GET {{BASE_URL}}/products

### GET Products and filter ###
GET {{BASE_URL}}/products/filter?category=technology

### POST Product ###
POST {{BASE_URL}}/products
Content-Type: application/json

{
    "name": "Test Product 8",
    "desc": "Test PRoduct 8 description",
    "sku": "TP8",
    "price": 20.12,
    "qty": 20
}

### GET Product ###
GET {{BASE_URL}}/products/b60b4434-7c73-4905-bf4f-cc74dd8ffd13

### UPDATE Product ###
PUT {{BASE_URL}}/products/163bee88-d55d-4e84-b292-fb42daa6173c
Content-Type: application/json

{
    "categories": ["design"]
}

### DELETE Product ###
DELETE  {{BASE_URL}}/products/b60b4434-7c73-4905-bf4f-cc74dd8ffd13


### GET Categories ###
GET {{BASE_URL}}/categories

### POST Category ###
POST {{BASE_URL}}/categories
Content-Type: application/json

{
    "name": "Technology",
    "desc": "Technology description"
}

### GET Category ###
GET {{BASE_URL}}/categories/4d1c531e-5abf-4418-9c0d-c81ad7ebe72e


### UPDATE Category ###
PATCH {{BASE_URL}}/categories/4d1c531e-5abf-4418-9c0d-c81ad7ebe72e
Content-Type: application/json

{
    "name": "Category 1 UPDATED"
}

### DELETE Category ###
DELETE {{BASE_URL}}/categories/4d1c531e-5abf-4418-9c0d-c81ad7ebe72e