@CARTS_URL=http://localhost:5000/api/v1/carts

### GET Carts ###
GET {{CARTS_URL}}

### CREATE Cart ###
POST {{CARTS_URL}}

### GET Cart ###
GET {{CARTS_URL}}/0cfd6676-a1bf-48da-8a71-a33635682f78

### PUT Cart ###
PUT {{CARTS_URL}}/fe06afb2-4090-4aef-89a6-159a769dc7af


### DELETE Cart ###
DELETE {{CARTS_URL}}/c1d417d9-00e2-4858-9286-2eb6f4997a57