@ORDERS_URL=http://localhost:5000/api/v1/orders

### GET All Orders ###
GET {{ORDERS_URL}}

### CREATE Order ###
POST {{ORDERS_URL}}
Content-Type: application/json

{
    "total": 20.55
}

### GET Order ###
GET {{ORDERS_URL}}/7f5bd8e9-1edd-48f0-9641-48144c8f573b

### PATCH Order ###
PATCH {{ORDERS_URL}}/7f5bd8e9-1edd-48f0-9641-48144c8f573b
Content-Type: application/json

{
    "total": 19.55
}

### DELETE Order ###
DELETE {{ORDERS_URL}}/7f5bd8e9-1edd-48f0-9641-48144c8f573b