@AUTH_URL=http://localhost:5000/api/v1/auth

### REGISTER User ###
POST {{AUTH_URL}}/register
Content-Type: application/json

{
    "firstName": "Ernest",
    "lastName": "Wambua",
    "email": "ernestwambua@gmail.com",
    "phone": "+254719286396",
    "password": "EGhtyPo3478!"
}

### LOGIN Admin User ###
POST {{AUTH_URL}}/login
Content-Type: application/json

{
    "email": "admin@ecommdb.com",
    "password": "Op76!hgh90@"
}

### LOGIN Normal User ###
POST {{AUTH_URL}}/login
Content-Type: application/json

{
    "email": "ernestwambua@gmail.com",
    "password": "EGhtyPo3478!"
}

### GET User Profile ###
GET {{AUTH_URL}}/profile

### LOGOUT User ###
GET {{AUTH_URL}}/logout